language: node_js
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - "6"
  - "8"
  - "10"
notifications:
    email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
