language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.npm-cache
    - node_modules
node_js:
  - "6"
  - "8"
  - "10"
before_install:
  - if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
install:
  - npm ci
notifications:
    email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
