language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.npm-cache
    - node_modules
node_js:
  - "4"
  - "6"
  - "8"
  - "10"
before_install:
  - command -v npx >/dev/null 2>&1 || npm i --silent -g npx
install:
  - npx npm@6 ci
before_script: [ `node -v` = v4* ] && JEST_ENV=node || JEST_ENV=jsdom
script: npx jest --ci --coverage --env=$JEST_ENV
notifications:
    email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
