language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.npm-cache
    - node_modules
node_js:
  - "6"
  - "8"
  - "10"
before_install:
  - command -v npx >/dev/null 2>&1 || npm i --silent -g npx
install:
  - npx npm@6 ci
script: npx jest --ci --coverage
notifications:
    email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
