install:
  - ps: Install-Product node 10 x64
  - npm install --silent --global npx
  - set PATH=%APPDATA%\npm;%PATH%
  - npx npm@6 ci --silent >nul
build: off
test_script:
  - rem *********** Using node 4 ***********
  - npx -p node@4 npm rebuild >nul
  - npx -p node@4 jest --ci --env=node

  - rem *********** Using node 6 ***********
  - npx -p node@6 npm rebuild >nul
  - npx -p node@6 jest --ci

  - rem *********** Using node 8 ***********
  - npx -p node@8 npm rebuild >nul
  - npx -p node@8 jest --ci

  - rem *********** Using node 10 ***********
  - npx -p node@10 npm rebuild >nul
  - npx -p node@10 jest --ci --coverage
after_test:
  - npx codecov
cache:
  - '%AppData%/npm-cache'
  - '%AppData%/npm'
