environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '8'
    - nodejs_version: '6'
install:
  - yarn install
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - node --version
  - yarn --version
  - yarn test
cache:
  - '%LOCALAPPDATA%\Yarn'
