environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"
install:
  - ps: Install-Product node $env:nodejs_version
  - npx >nul 2>&1 || ( npm install --silent --global npx )
  - set PATH=%APPDATA%\npm;%PATH%
  - npx npm@6 ci
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - npm test
cache:
  - node_modules
  - '%AppData%/npm-cache'
  - '%AppData%/npm'
