environment:
  matrix:
    - node_arch: "x64"
install:
  - ps: Install-Product node 10 $env:node_arch
  - npm install --silent --global npx
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --silent >nul
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - rem *********** Using node 4 ***********
  - npx -p node@4 npm rebuild >nul
  - npx -p node@4 jest --ci --env=node

  - rem *********** Using node 6 ***********
  - npx -p node@6 npm rebuild >nul
  - npx -p node@6 jest --ci

  - rem *********** Using node 8 ***********
  - npx -p node@8 npm rebuild >nul
  - npx -p node@8 jest --ci

  - rem *********** Using node 10 ***********
  - npx -p node@10 npm rebuild >nul
  - npx -p node@10 jest --ci --coverage
cache:
  - node_modules
  - '%AppData%/npm-cache'
  - '%AppData%/npm'
